Move git plugin clone before pkg installation

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -55,11 +55,6 @@ install_template: &INSTALL_PLUGIN
       done
     done
 
-    echo "Test install plugin pkgs for plugin: $name"
-    pkgs=$(jq -r '.pkgs | join(" ")' $PLUGIN_FILE)
-    echo "Installing $name pkgs: $pkgs"
-    pkg install -y $pkgs
-
     if [ "$(which git)" = "" ]
     then
       pkg install -y git-lite || pkg install -y git
@@ -68,16 +63,22 @@ install_template: &INSTALL_PLUGIN
     release_branch="$(freebsd-version | cut -d '-' -f1)-RELEASE"
     git clone -b ${release_branch} ${plugin_repo} ./plugin || git clone -b master ${plugin_repo} ./plugin
 
+    # Cleanup before plugin pkg installation
+    if ! echo ${pkgs} | grep -q "git"
+    then
+      pkg remove -y git-lite git jq
+      pkg autoremove -y
+    fi
+
+    echo "Test install plugin pkgs for plugin: $name"
+    pkgs=$(jq -r '.pkgs | join(" ")' $PLUGIN_FILE)
+    echo "Installing $name pkgs: $pkgs"
+    pkg install -y $pkgs
+
     if [ -d "./plugin/overlay" ]
     then
       echo "Found overlay folder"
       cp -r ./plugin/overlay/ /
-    fi
-
-    if ! echo ${pkgs} | grep -q "git"
-    then
-      pkg remove -y git-lite git
-      pkg autoremove -y
     fi
 
     ./plugin/post_install.sh
