Retry admin portal fetch 10 times with 5 s. sleep

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -8,7 +8,31 @@ install_template: &INSTALL_PLUGIN
     if [ -f ./plugin/ui.json ]
     then
       admin_portal=$(jq -r '.adminportal' ./plugin/ui.json | sed 's/%%IP%%/localhost/')
-      fetch ${admin_portal}
+
+      max_retries=10
+      retry=0
+      fetch_success=false
+      sleep_time=5
+
+      while [$retry -lt $max_retires]
+      do
+        if fetch ${admin_portal} 2> /dev/null
+        then
+          fetch_success=true
+          break
+        fi
+
+        echo "Admin UI fetch failed, sleeping ${sleep_time} seconds, and retrying"
+        sleep ${sleep_time}
+      done
+
+      if fetch_success
+      then
+        echo "Admin Portal reachable"
+      else
+        echo "Could not fetch Admin Portal"
+        exit 1
+      fi
     fi
 
 backuppc_task:
